"""
Response Caching Layer
In-memory cache with TTL for LLM response deduplication.
"""

import hashlib
import time
from typing import Optional


class ResponseCache:
    """
    In-memory response cache with TTL (time-to-live).

    In production, replace this with Redis for:
    - Persistence across restarts
    - Shared cache across multiple instances
    - Built-in TTL management
    """

    '''
    The ResponseCache class provides a simple in-memory caching mechanism for LLM responses. 
    It uses a dictionary to store cached responses along with their timestamps, allowing for 
    TTL-based expiration. The cache keys are generated by normalizing the input query 
    (case-insensitive and stripped of whitespace) and hashing it to ensure consistent and 
    efficient lookups.
    
    Key features:
    - TTL Management: Cached entries expire after a specified time, ensuring that stale data is not
      returned.
    - Case-Insensitive Keys: Queries are normalized to ensure that different variations of the same query
      (e.g., 'What is Python?' and 'what is python?') map to the same cache entry.
    - Performance Statistics: The cache tracks hits, misses, and hit rate, providing insights into cache
      performance.

    Usage:
      The example usage demonstrates how to interact with the ResponseCache, including cache hits, misses,
      and TTL expiration. This can be used as a basis for integrating the cache into your application,
      allowing you to cache LLM responses and improve performance by avoiding redundant calls for the same
      queries.
      
    Note:
      - In a production environment, consider using a more robust caching solution like Redis, which offers
        persistence, shared access across multiple instances, and built-in TTL management.  
    
    '''

    def __init__(self, ttl_seconds: int = 300):
        self.ttl = ttl_seconds
        self._cache: dict[str, dict] = {}
        self._hits = 0
        self._misses = 0

    def _make_key(self, query: str) -> str:
        """Create a cache key from the normalized query."""
        normalized = query.lower().strip()

        # Use SHA-256 hash to create a fixed-length key from the normalized query
        # This ensures that different variations of the same query (e.g., 'What is Python?' and 'what is python?')
        # will map to the same cache entry, while also providing a consistent key format.
        return hashlib.sha256(normalized.encode()).hexdigest()

    # 'What is Python?' and 'what is python?'

    def get(self, query: str) -> Optional[str]:
        """
        Get cached response if it exists and hasn't expired.
        Returns None on cache miss.
        """
        key = self._make_key(query)

        # This is not production grade TTL management, but it demonstrates the concept. 
        # In a real application, you would want to use a more robust caching solution 
        # like Redis, which handles TTL automatically.
        if key in self._cache:
            entry = self._cache[key]
            # Check TTL
            if time.time() - entry["timestamp"] < self.ttl:
                self._hits += 1
                return entry["response"]
            else:
                # Expired - remove it
                del self._cache[key]

        self._misses += 1
        return None

    def set(self, query: str, response: str) -> None:
        """Cache a response."""
        key = self._make_key(query)
        self._cache[key] = {
            "response": response,
            "timestamp": time.time(),
            "query": query,
        }

    @property
    def stats(self) -> dict:
        """Cache performance statistics."""
        total = self._hits + self._misses
        hit_rate = self._hits / total if total > 0 else 0.0
        return {
            "hits": self._hits,
            "misses": self._misses,
            "hit_rate": f"{hit_rate:.1%}",
            "cached_entries": len(self._cache),
        }






# uv run python -c "
# import time
# from app.cache import ResponseCache

# cache = ResponseCache(ttl_seconds=3)  # Short TTL for demo

# print('=== CACHE DEMO ===')
# print()

# # Miss
# result = cache.get('What is Python?')
# print(f'1. First lookup: {result}  (miss - nothing cached yet)')

# # Store
# cache.set('What is Python?', 'Python is a programming language.')
# print(f'2. Stored response in cache')

# # Hit
# result = cache.get('What is Python?')
# print(f'3. Second lookup: {result}  (HIT!)')

# # Case insensitive
# result = cache.get('what is python?')
# print(f'4. Lowercase lookup: {result}  (HIT - case insensitive!)')

# # Different query = miss
# result = cache.get('What is JavaScript?')
# print(f'5. Different query: {result}  (miss)')

# # Stats
# print(f'6. Stats: {cache.stats}')

# # Wait for TTL
# print(f'7. Waiting 4 seconds for TTL expiration...')
# time.sleep(4)

# result = cache.get('What is Python?')
# print(f'8. After TTL: {result}  (miss - expired!)')
# print(f'9. Final stats: {cache.stats}')
# "
